### ISSUE TITLE
What is the dimension of the embeddings?

### ISSUE THREAD

**Issue by hehao13** [Weixin-Liang/MetaShift#3]
Hello, thank you for the nice and instructive work. 

There are two questions I'd like to ask.

First, what is the dimension (K in the paper) of each embedding?
Second, when assigning one embedding for each node, what package did you use, Sklearn or others? 

Thanks !

**Comment by Weixin-Liang** [comment]
Hi please check out this function, which visualizes the meta graphs. The graph embedding generation should be similar. https://github.com/Weixin-Liang/MetaShift/blob/main/dataset/generate_full_MetaShift.py#L155
 
 I used networkx spectral_layout with a small K like 10.
