### ISSUE TITLE
Spectral layout dimensions

### ISSUE THREAD

**Issue by IbtihalFerwana** [Weixin-Liang/MetaShift#6]
Hello, thanks for making your code and dataset available!

I have a question about the file `domain_generalization_cat_dog.py` at line https://github.com/Weixin-Liang/MetaShift/blob/916421d572bde555615bfa71b2ff8f1da76ac8a3/dataset/domain_generalization_cat_dog.py#L222-L225
Can you please guide me how do you pick the dimension for the spectral layout? I wonder because I was changing the datasets and selecting less subsets which raised an error on the dimension number. 

Thanks.

**Comment by Weixin-Liang** [comment]
Thank you for your interest. 

The following material on the graph spectral embedding might be useful: 
> ## Spectral Graph Theory
> Lecture 11 (Mon 5/3): Graphs as matrices and the Laplacian of a graph. Interpretations of the largest and smallest eigenvectors/eigenvalues of the Laplacian. Spectral embeddings, and an overview of applications (e.g. graph coloring, spectral clustering.)
> - [Lecture notes.](https://web.stanford.edu/class/cs168/l/l11.pdf)

> Lecture 12 (Wed 5/5): Spectral techniques, Part 2. Interpretations of the second eigenvalue (via conductance and isoperimetric number), and connections with the speed at which random walks/diffusions converge.
> - [Lecture notes.](https://web.stanford.edu/class/cs168/l/l12.pdf)

Basically, the `spectral node embedding` can be viewed as some kind of `eigenvector`. If the number of nodes is small, the rank of the `graph Laplacian matrix` would be small too. Therefore, there are fewer eigenvectors with non-zero eigenvalues. 

So in short, if you want to increase the dimension of the spectral node embedding, maybe you need to consider having more nodes in the meta-graph.
