### ISSUE TITLE
How to select subsets of indoor and outdoor in subpopulation experiment

### ISSUE THREAD

**Issue by litingfeng** [Weixin-Liang/MetaShift#7]
Hi,

Thanks for contributing the great project!

I have a question regarding how you selected the subsets belonging to indoor and outdoor.  While we can find corresponding subset name specified by attributes like "dog(white)" in `attributes-candidate-subsets.pkl`, it looks like you specified the **indoor** and **outdoor** manually in [this](https://github.com/Weixin-Liang/MetaShift/blob/916421d572bde555615bfa71b2ff8f1da76ac8a3/dataset/subpopulation_shift_cat_dog_indoor_outdoor.py#L182) file.

I was wondering how you generate `train_set_scheme` and `test_set_scheme`. What if we want to select cat & dog with other contexts in GENERAL_CONTEXT_ONTOLOGY, e.g., cat(bedroom)? I also noticed there is a file `obj2attribute.json`. Could you please provide some instructions on how to utilize it? 

Thanks,
Ting

**Comment by Weixin-Liang** [comment]
Hi, thank you for your interest in our work. 

As mentioned in the paper, the subsets are selected based on the node community detection results on the meta-graph.

> **Section 4.1: Evaluating domain generalization**
> To make our evaluation settings more challenging, we merge similar subsets by running Louvain community detection algorithm (Blondel et al., 2008) on each meta-graph. Node color in Figure 2 indicates the community detection result.
> ![image](https://user-images.githubusercontent.com/32794044/160027088-c0bdf045-d812-4419-a5e3-15c340ae7ee5.png)

In the code, the [`print_communities` function](https://github.com/Weixin-Liang/MetaShift/blob/916421d572bde555615bfa71b2ff8f1da76ac8a3/dataset/subpopulation_shift_cat_dog_indoor_outdoor.py#L77) provides the node community detection results. In practice, the community detection results tend to capture fine-grained communities. For example, although both `cat(computer)` and `cat(sink)` are indoor, they are assigned to two different communities as indicated by their node color. Therefore, for contexts that are more abstract (e.g., indoor or outdoor), you may need to manually group multiple communities together.
