### ISSUE TITLE
dog(ocean) or ocean(dog)?

### ISSUE THREAD

**Issue by muliyangm** [Weixin-Liang/MetaShift#8]
Thank you for this great work!

I was recently playing with `understanding_full-candidate-subsets-pkl.ipynb` and I found that `full-candidate-subsets.pkl` also contains some general contexts subsets like `ocean(dog)` (as mentioned in the `.ipynb`). Thus I tried to search for `dog(ocean)` yet with no outcomes. Similarly I found some other subsets, e.g., `dog(cat)` and `cat(dog)`, are coupled as a two-way style. Here my questions are
1. What is the logic behind involving these two-way subsets like `dog(cat)` and `cat(dog)`? Is it based on the object saliency such that the images in the subset can be depicted as `foreground(background)`?
1. Not all two-way subsets are presented in `full-candidate-subsets.pkl`, e.g., there is `ocean(dog)`, yet no `dog(ocean)`. Is it simply because the `dog(ocean)` images are less than 25, or if the answer to Q1 is yes, dogs are overall less salient in images?

Thanks for your attention!

**Comment by muliyangm** [comment]
ps. I further dug into the source image folders and I found that `dog(cat)` and `cat(dog)` contain the same set of images.

**Comment by Weixin-Liang** [comment]
Thank you for your interest. 

It seems this is related to: https://github.com/Weixin-Liang/MetaShift/issues/1

We haven't done object saliency filtering, but if you need, it is possible to filter based on object saliency by using the bounding box information from the scene graphs in GQA https://cs.stanford.edu/people/dorarad/gqa/download.html

Indeed, as you observed, sometimes `A(B)` is included but `B(A)` is not included. There is nothing too special about it. Perhaps an easy workaround is to search for both `A(B)` and `B(A)` at the same time and take whatever exists.
